"""Add onboarding_completed to users

Revision ID: 2f5bab9bf639
Revises: 4f5124c4824c
Create Date: 2025-11-26 17:18:04.130553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5bab9bf639'
down_revision: Union[str, None] = '4f5124c4824c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prompt_versions_prompt_id_fkey', 'prompt_versions', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_versions', 'prompts', ['prompt_id'], ['id'])
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.create_foreign_key('prompt_versions_prompt_id_fkey', 'prompt_versions', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
