"""Add is_active field to product_api_keys

Revision ID: 6ceee9ea71f0
Revises: f25d4162df80
Create Date: 2025-09-13 09:06:16.155054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ceee9ea71f0'
down_revision: Union[str, None] = 'f25d4162df80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_api_keys', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_api_keys', 'is_active')
    # ### end Alembic commands ###
