"""add_conversion_funnels_table

Revision ID: 71e443dffd3e
Revises: f0adcbd89904
Create Date: 2025-09-24 12:11:58.395062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71e443dffd3e'
down_revision: Union[str, None] = 'f0adcbd89904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_funnels',
        sa.Column('id', sa.UUID(), nullable=False, default=sa.text('gen_random_uuid()')),
        sa.Column('workspace_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('source_event_name', sa.String(length=100), nullable=True),
        sa.Column('source_prompt_id', sa.UUID(), nullable=True),
        sa.Column('target_event_name', sa.String(length=100), nullable=False),
        sa.Column('target_event_category', sa.String(length=100), nullable=True),
        sa.Column('metric_type', sa.String(length=50), nullable=False),
        sa.Column('metric_field', sa.String(length=100), nullable=True),
        sa.Column('conversion_window_hours', sa.Integer(), nullable=True, default=24),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('color', sa.String(length=7), nullable=True, default='#3B82F6'),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True, default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['source_prompt_id'], ['prompts.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'name', name='uq_conversion_funnel_workspace_name')
    )
    op.create_index('idx_conversion_workspace', 'conversion_funnels', ['workspace_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversion_workspace', table_name='conversion_funnels')
    op.drop_table('conversion_funnels')
    # ### end Alembic commands ###