"""Add public_shares table for prompt sharing

Revision ID: 96902101434f
Revises: 6ceee9ea71f0
Create Date: 2025-09-17 22:43:44.032548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96902101434f'
down_revision: Union[str, None] = '6ceee9ea71f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
