"""add_trace_id_to_product_api_log

Revision ID: ae810c6b31a3
Revises: 71e443dffd3e
Create Date: 2025-09-24 12:23:12.047059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ae810c6b31a3'
down_revision: Union[str, None] = '71e443dffd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_api_logs', sa.Column('trace_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_product_api_logs_trace_id'), 'product_api_logs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_api_logs_trace_id'), table_name='product_api_logs')
    op.drop_column('product_api_logs', 'trace_id')
    # ### end Alembic commands ###