"""Restore event_definitions and prompt_events tables

Revision ID: ee91042ef174
Revises: 028d183da5b9
Create Date: 2025-09-21 19:43:25.463647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee91042ef174'
down_revision: Union[str, None] = '028d183da5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Create missing tables ###
    # Create event_definitions table
    op.create_table('event_definitions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('workspace_id', sa.UUID(), nullable=False),
        sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
        sa.Column('category', sa.VARCHAR(length=100), nullable=True),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('optional_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('alert_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.BOOLEAN(), nullable=True, default=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True, server_default=sa.func.now()),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'event_name')
    )

    # Create prompt_events table
    op.create_table('prompt_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('workspace_id', sa.UUID(), nullable=False),
        sa.Column('trace_id', sa.VARCHAR(length=100), nullable=False),
        sa.Column('prompt_id', sa.UUID(), nullable=True),
        sa.Column('prompt_version_id', sa.UUID(), nullable=True),
        sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
        sa.Column('outcome', sa.VARCHAR(length=50), nullable=True),
        sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
        sa.Column('user_id', sa.VARCHAR(length=255), nullable=True),
        sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('business_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True, server_default=sa.func.now()),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
        sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes
    op.create_index('ix_prompt_events_trace_id', 'prompt_events', ['trace_id'], unique=True)
    op.create_index('idx_events_workspace_created', 'prompt_events', ['workspace_id', 'created_at'], unique=False)
    op.create_index('idx_events_prompt_outcome', 'prompt_events', ['prompt_id', 'outcome', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_metrics_hourly',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prompt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('hour_bucket', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('successful_outcomes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_outcomes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partial_outcomes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abandoned_outcomes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_revenue', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('conversion_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='prompt_metrics_hourly_prompt_id_fkey'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name='prompt_metrics_hourly_prompt_version_id_fkey'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='prompt_metrics_hourly_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='prompt_metrics_hourly_pkey'),
    sa.UniqueConstraint('workspace_id', 'prompt_id', 'prompt_version_id', 'hour_bucket', name='prompt_metrics_hourly_workspace_id_prompt_id_prompt_version_key')
    )
    op.create_index('idx_metrics_workspace_hour', 'prompt_metrics_hourly', ['workspace_id', 'hour_bucket'], unique=False)
    op.create_index('idx_metrics_prompt_hour', 'prompt_metrics_hourly', ['prompt_id', 'hour_bucket'], unique=False)
    op.create_table('prompt_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('business_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='prompt_events_prompt_id_fkey'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name='prompt_events_prompt_version_id_fkey'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='prompt_events_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='prompt_events_pkey')
    )
    op.create_index('ix_prompt_events_trace_id', 'prompt_events', ['trace_id'], unique=False)
    op.create_index('idx_events_workspace_created', 'prompt_events', ['workspace_id', 'created_at'], unique=False)
    op.create_index('idx_events_prompt_outcome', 'prompt_events', ['prompt_id', 'outcome', 'created_at'], unique=False)
    op.create_table('ab_tests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prompt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('control_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('variant_version_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False),
    sa.Column('traffic_allocation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics_to_track', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('winner_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('statistical_significance', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('sample_size_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_sample_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['control_version_id'], ['prompt_versions.id'], name='ab_tests_control_version_id_fkey'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='ab_tests_prompt_id_fkey'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='ab_tests_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ab_tests_pkey')
    )
    op.create_table('event_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('optional_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('alert_thresholds', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='event_definitions_created_by_fkey'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='event_definitions_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='event_definitions_pkey'),
    sa.UniqueConstraint('workspace_id', 'event_name', name='event_definitions_workspace_id_event_name_key')
    )
    # ### end Alembic commands ###
