"""remove_use_global_limits_field

Revision ID: f25d4162df80
Revises: d370d97a8d54
Create Date: 2025-09-10 22:11:29.552077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25d4162df80'
down_revision: Union[str, None] = 'd370d97a8d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_limits', 'use_global_limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_limits', sa.Column('use_global_limits', sa.BOOLEAN(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###
