apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    access: proxy
    url: postgres:5432
    user: xr2_user
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      database: xr2_db
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    uid: Prometheus
    url: http://prometheus:9090/prometheus
    access: proxy
    isDefault: false
    editable: true
